### ISSUE TITLE
Returning to Website from Mailchilmb registration not working

### ISSUE THREAD

**Issue by royalcas** [angular-medellin/ng-colombia#2]
When we `subscribe` to the newsletter we are redirected to the mailchimb main page.

When we finish filling the form it shows us a button for returning to the main page.

It should return to the ng colombia page but now it is returning to another one:

![image](https://user-images.githubusercontent.com/7102342/31181214-661f091c-a8e6-11e7-9df1-54e0f37914e2.png)

Redirected to>
http://www.juandavidherrera.com/

**Comment by jdjuan** [comment]
Thanks! 😅 

Fixed! 😉
